/**
 * 内置示例路线卡。新建分身的 Palace 时种入，避免“宫殿空房子”——
 * 让用户一开始就有可参照、可改写的路线卡样例。已存在的同名卡不会被覆盖。
 */

import { PALACE_SCHEMA_VERSION, type PalaceRoom } from './types'

export function buildExamplePalaceRooms(now: Date = new Date()): PalaceRoom[] {
  const iso = now.toISOString()
  const base = {
    schemaVersion: PALACE_SCHEMA_VERSION,
    enabled: true,
    requiresContextCard: true,
    createdAt: iso,
    updatedAt: iso,
  } as const

  return [
    {
      ...base,
      id: 'daily-room',
      name: '今日驾驶舱',
      description: '一天开始时给出今日聚焦：当前重点 + 到期承诺 + 近期会议，最多 3 件事。',
      triggers: ['今天该干啥', '今日聚焦', '今日驾驶舱', '今天做什么', '日程'],
      priority: 80,
      requiredFiles: ['profile.md', 'commitments.json', 'meetings/', 'reports/'],
      readOrder: [
        'profile.md：当前重点，给今天定基调',
        'commitments.json：逾期/到期的承诺，今天必须推进的',
        'meetings/：今天与未来 3 天的会议',
        'reports/：最新周报的“下周计划”',
      ],
      conditionalReads: [
        '涉及对外汇报 → 重点看最新 reports/ 与对方 people/ 画像',
        '有逾期承诺 → 先看 commitments 里 overdue 的，今天优先清',
      ],
      pitfalls: ['3 件事是硬上限，不凑数', '输出不超一屏', '没把握的别替用户承诺工期'],
      outputLocation: 'inbox/',
      toneGuidance: '简洁、聚焦、像顶级助理张口给重点，不堆材料。',
      sedimentTargets: ['inbox'],
      body: [
        '# 今日驾驶舱',
        '',
        '## 触发场景',
        '- 用户说“今天该干啥”“今日聚焦”，或一天首次打开。',
        '',
        '## 必读，按顺序',
        '1. profile.md：当前重点，给今天定基调',
        '2. commitments.json：逾期/到期的承诺',
        '3. meetings/：今天与未来 3 天的会议',
        '4. reports/：最新周报的“下周计划”',
        '',
        '## 条件读',
        '- 涉及对外汇报 → 重点看最新 reports/ 与对方 people/ 画像',
        '- 有逾期承诺 → 先清 overdue',
        '',
        '## 坑',
        '- 3 件事是硬上限，不凑数',
        '- 不超一屏',
        '',
      ].join('\n'),
    },
    {
      ...base,
      id: 'report-room',
      name: '写周报 / 汇报',
      description: '准备周报或向上汇报：先拉指标和成果，再按对方偏好组织口径。',
      triggers: ['写周报', '周报', '写汇报', '准备汇报', '月报', '述职'],
      priority: 70,
      requiredFiles: ['profile.md', 'reports/', 'achievements/', 'commitments.json'],
      readOrder: [
        'reports/：上一期周报，承接“下周计划”',
        'achievements/：本周可用的成果素材',
        'commitments.json：本周交付/到期的承诺',
        'profile.md：当前重点，确认汇报主线',
      ],
      conditionalReads: [
        '汇报对象是老板 → 看 people/ 里他的偏好（只看数字/要结论先行）',
        '涉及延期项目 → 主动提一句进展，别等对方问',
      ],
      pitfalls: ['先给结论和数字，过程往后放', '别把没做完的写成已完成', '数据要可溯源'],
      outputLocation: 'reports/',
      toneGuidance: '结论先行、数字说话；对老板用“三个关键指标 + 风险点”的结构。',
      sedimentTargets: ['reports', 'achievements', 'inbox'],
      body: [
        '# 写周报 / 汇报',
        '',
        '## 触发场景',
        '- 用户说“写周报”“准备汇报”“述职”。',
        '',
        '## 必读，按顺序',
        '1. reports/ 上一期，承接“下周计划”',
        '2. achievements/ 本周成果素材',
        '3. commitments.json 本周交付/到期',
        '4. profile.md 确认汇报主线',
        '',
        '## 条件读',
        '- 汇报对象是老板 → 看他的偏好画像',
        '- 涉及延期项目 → 主动提进展',
        '',
        '## 坑',
        '- 结论先行，过程往后放',
        '- 不把未完成写成已完成',
        '',
      ].join('\n'),
    },
    {
      ...base,
      id: 'conflict-room',
      name: '组织冲突沟通',
      description: '处理跨团队/向上冲突：先理清立场和利益关系，再给风险矩阵与沟通策略。',
      triggers: ['冲突', '撕', '扯皮', '职责边界', '抢活', '甩锅', '向上沟通'],
      priority: 60,
      requiredFiles: ['profile.md', 'company.md', 'people/'],
      readOrder: [
        'profile.md：核心职责 + 当前重点，确认我的立场和职责范围',
        'company.md：组织结构 + 相关协作组，理解各方定位和利益关系',
        'company.md：关键领导，了解决策链路，判断谁能拍板',
        'people/：相关人员画像，了解对方诉求、风格、历史互动',
      ],
      conditionalReads: [
        '涉及职责边界 → 用具体事项做锚点（如“某能力归谁”），不只讲抽象原则',
        '已有冲突记录 → 先看 decisions/ 里的历史结论',
        '需要向上升级 → 先确认直属领导情绪与支持，避免越级',
      ],
      pitfalls: [
        '不要假设对方是恶意的——多数冲突源于信息不对称和目标不对齐',
        '分析冲突必须同时给出对方的合理立场，否则会变成单边叙事',
        '涉及具体人名和敏感判断时打 ⚠ 标记，提醒用户确认后再行动',
      ],
      outputLocation: 'decisions/',
      toneGuidance: '中立、对事不对人；先复述对方的合理立场，再给己方策略；敏感处标 ⚠。',
      sedimentTargets: ['decisions', 'people', 'inbox'],
      body: [
        '# 组织冲突沟通',
        '',
        '## 触发场景',
        '- 用户描述跨团队扯皮、职责边界争议、需要向上沟通的冲突。',
        '',
        '## 必读，按顺序',
        '1. profile.md：核心职责 + 当前重点',
        '2. company.md：组织结构 + 相关协作组',
        '3. company.md：关键领导，判断谁能拍板',
        '4. people/：相关人员画像',
        '',
        '## 条件读',
        '- 涉及职责边界 → 用具体事项做锚点',
        '- 已有冲突记录 → 先看 decisions/ 历史结论',
        '- 需要升级 → 先确认直属领导支持，避免越级',
        '',
        '## 坑',
        '- 不要假设对方是恶意的',
        '- 必须同时给出对方的合理立场',
        '- 敏感判断打 ⚠ 标记',
        '',
      ].join('\n'),
    },
  ]
}
