#!/usr/bin/env python3
"""
Phase 0.1 + 0.2 — 知识库 token 实测 + 三档分类

用 tiktoken o200k_base（GPT-4o BPE，与 Claude 4 / DeepSeek V3+ 实际 token 数偏差 ±10% 内）
扫描所有 expert-pack 的 knowledge/ 目录，输出：
  - <pack>/tokens.tsv —— 每个文件的 token 数（调试用）
  - report.md         —— markdown 汇总报告
  - routing-table.yaml—— 按三档分类的路由表

跳过：_raw/（二进制原文件）、images/（图片）、.git/、node_modules/
计入：*.md（主要载体）、_excel/*.json（结构化 excel 数据，via query_excel 可被读取）
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Dict, List, Tuple

try:
    import tiktoken
except ImportError:
    print("ERROR: tiktoken not installed. Run: pip3 install --user tiktoken", file=sys.stderr)
    sys.exit(1)

ROOT = Path("/Users/kian/备份/AI/soul")
EXPERT_PACKS = ROOT / "expert-packs"
SHARED_KNOWLEDGE = ROOT / "shared" / "knowledge"
OUT_DIR = ROOT / ".cursor" / "plans" / "phase0-token-survey"

SKIP_DIRS = {"_raw", "images", ".git", "node_modules", "__pycache__"}

ENC = tiktoken.get_encoding("o200k_base")


def count_file_tokens(path: Path) -> int:
    """Read file as utf-8 (lossy on bad bytes), return BPE token count."""
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except (OSError, UnicodeError) as e:
        print(f"  skip {path}: {e}", file=sys.stderr)
        return 0
    return len(ENC.encode(text, disallowed_special=()))


def walk_knowledge(root: Path) -> List[Tuple[Path, int, str]]:
    """Walk a knowledge/ dir. Return [(relpath, tokens, category)]."""
    results: List[Tuple[Path, int, str]] = []
    for dirpath, dirnames, filenames in os.walk(root):
        # in-place prune so we never descend into _raw / images
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for fn in filenames:
            full = Path(dirpath) / fn
            rel = full.relative_to(root)
            if fn.endswith(".md"):
                category = "md"
            elif fn.endswith(".json") and "_excel" in str(rel):
                category = "excel_json"
            else:
                continue
            results.append((rel, count_file_tokens(full), category))
    return results


def classify(tokens: int) -> str:
    if tokens < 500_000:
        return "small"
    if tokens < 1_000_000:
        return "medium"
    return "large"


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    # shared/knowledge first (everyone sees it)
    print("Scanning shared/knowledge ...", file=sys.stderr)
    shared_files = walk_knowledge(SHARED_KNOWLEDGE) if SHARED_KNOWLEDGE.exists() else []
    shared_md = sum(t for _, t, c in shared_files if c == "md")
    shared_excel = sum(t for _, t, c in shared_files if c == "excel_json")

    packs: Dict[str, Dict] = {}
    for pack_dir in sorted(EXPERT_PACKS.iterdir()):
        if not pack_dir.is_dir():
            continue
        knowledge_dir = pack_dir / "knowledge"
        if not knowledge_dir.exists():
            continue
        print(f"Scanning {pack_dir.name} ...", file=sys.stderr)
        files = walk_knowledge(knowledge_dir)

        md_tokens = sum(t for _, t, c in files if c == "md")
        excel_tokens = sum(t for _, t, c in files if c == "excel_json")

        # per-pack file dump (sortable for top-N reporting)
        tsv_lines = ["category\ttokens\trelpath"]
        for rel, tok, cat in sorted(files, key=lambda x: -x[1]):
            tsv_lines.append(f"{cat}\t{tok}\t{rel}")
        (OUT_DIR / f"tokens_{pack_dir.name}.tsv").write_text(
            "\n".join(tsv_lines), encoding="utf-8"
        )

        own_total = md_tokens + excel_tokens
        effective_md_only = md_tokens + shared_md
        effective_full = own_total + shared_md + shared_excel

        packs[pack_dir.name] = {
            "file_count": len(files),
            "md_tokens": md_tokens,
            "excel_tokens": excel_tokens,
            "own_total_tokens": own_total,
            "effective_md_only": effective_md_only,
            "effective_full": effective_full,
            "tier_md_only": classify(effective_md_only),
            "tier_full": classify(effective_full),
            "top10": [
                {"category": c, "tokens": t, "path": str(r)}
                for r, t, c in sorted(files, key=lambda x: -x[1])[:10]
            ],
        }

    # ---- write routing-table.yaml ----
    yaml_lines = [
        "# Phase 0.2 routing table — generated by count_tokens.py",
        "# Tier rules (effective tokens incl. shared/knowledge):",
        "#   small  : <500k    → Phase 2 prompt-cache full-context",
        "#   medium : 500k-1M  → boundary, evaluate case by case",
        "#   large  : >=1M     → Phase 3 BM25 + rerank + agentic",
        f"# shared_knowledge_md_tokens: {shared_md}",
        f"# shared_knowledge_excel_tokens: {shared_excel}",
        "",
        "shared:",
        f"  md_tokens: {shared_md}",
        f"  excel_tokens: {shared_excel}",
        "",
        "avatars:",
    ]
    for name, info in sorted(packs.items(), key=lambda x: -x[1]["effective_full"]):
        yaml_lines.append(f"  {json.dumps(name, ensure_ascii=False)}:")
        yaml_lines.append(f"    md_tokens: {info['md_tokens']}")
        yaml_lines.append(f"    excel_tokens: {info['excel_tokens']}")
        yaml_lines.append(f"    own_total: {info['own_total_tokens']}")
        yaml_lines.append(f"    effective_md_only: {info['effective_md_only']}")
        yaml_lines.append(f"    effective_full: {info['effective_full']}")
        yaml_lines.append(f"    tier_md_only: {info['tier_md_only']}")
        yaml_lines.append(f"    tier_full: {info['tier_full']}")
        yaml_lines.append(f"    file_count: {info['file_count']}")
    (OUT_DIR / "routing-table.yaml").write_text("\n".join(yaml_lines) + "\n", encoding="utf-8")

    # ---- write report.md ----
    sorted_packs = sorted(packs.items(), key=lambda x: -x[1]["effective_full"])
    report = [
        "# Phase 0 Token Survey — 知识库实测 + 三档分类",
        "",
        "**生成时间**: 自动生成（见脚本运行时）  ",
        "**Tokenizer**: tiktoken `o200k_base` (GPT-4o BPE, ≈ Claude 4 / DeepSeek V3+ ±10%)  ",
        "**统计范围**: `expert-packs/*/knowledge/**/*.md` + `_excel/**/*.json`；跳过 `_raw/`、`images/`",
        "",
        "## 分档规则",
        "",
        "| Tier | 阈值 | Phase 1+ 路由策略 |",
        "|---|---|---|",
        "| small | <500k tokens | 全文塞 system prompt + prompt cache（Phase 2.1） |",
        "| medium | 500k–1M | 边界值，逐个分身决定（Phase 2.3 size guard 触发） |",
        "| large | ≥1M | 保留 BM25 + rerank + agentic search tool（Phase 3） |",
        "",
        "## 共享知识库 (shared/knowledge)",
        "",
        f"- md tokens: **{shared_md:,}**",
        f"- _excel json tokens: **{shared_excel:,}**",
        f"- 每个分身的 effective 都会加上这部分",
        "",
        "## 分身排序（按 effective_full 降序）",
        "",
        "| 分身 | 自有 md | _excel json | own total | effective (md only) | effective (full) | tier (md only) | tier (full) |",
        "|---|---:|---:|---:|---:|---:|---|---|",
    ]
    for name, info in sorted_packs:
        report.append(
            f"| `{name}` "
            f"| {info['md_tokens']:,} "
            f"| {info['excel_tokens']:,} "
            f"| {info['own_total_tokens']:,} "
            f"| {info['effective_md_only']:,} "
            f"| {info['effective_full']:,} "
            f"| **{info['tier_md_only']}** "
            f"| **{info['tier_full']}** |"
        )

    # tier histogram
    tier_md_count = {"small": 0, "medium": 0, "large": 0}
    tier_full_count = {"small": 0, "medium": 0, "large": 0}
    for info in packs.values():
        tier_md_count[info["tier_md_only"]] += 1
        tier_full_count[info["tier_full"]] += 1
    report += [
        "",
        "## 分档分布",
        "",
        "| Tier | md only | with _excel |",
        "|---|---:|---:|",
        f"| small  | {tier_md_count['small']}  | {tier_full_count['small']} |",
        f"| medium | {tier_md_count['medium']} | {tier_full_count['medium']} |",
        f"| large  | {tier_md_count['large']}  | {tier_full_count['large']} |",
        "",
        "## 每分身 top-10 大文件",
        "",
    ]
    for name, info in sorted_packs:
        report.append(f"### {name}")
        report.append("")
        report.append("| # | category | tokens | path |")
        report.append("|---:|---|---:|---|")
        for i, item in enumerate(info["top10"], 1):
            report.append(f"| {i} | {item['category']} | {item['tokens']:,} | `{item['path']}` |")
        report.append("")

    report += [
        "## 观察 & 下一步建议",
        "",
        "- `tier_md_only` vs `tier_full` 不同 → 说明该分身的 `_excel/` 数据规模显著，决定它是否值得",
        "  全量入 prompt cache 时要把 excel 部分拆出来走 `query_excel` tool 路径",
        "- 处于 `medium` 档（500k–1M）的分身建议跑实际对话 P50 上下文窗口测量后再决定档位",
        "- `large` 档的分身在 Phase 3 BM25 路径里要进一步评估常驻 vs 按需加载",
        "",
        "## 输入到 Phase 1 的决策",
        "",
        "1. 哪些分身可以直接进 prompt-cache 全文路径（tier = small）",
        "2. 哪些必须保留 agentic search tool（tier = large）",
        "3. 边界分身（medium）的 routing 是否需要按对话场景动态切换",
    ]

    (OUT_DIR / "report.md").write_text("\n".join(report) + "\n", encoding="utf-8")

    print(f"\nDone. Outputs in {OUT_DIR}/", file=sys.stderr)
    print(f"  - routing-table.yaml ({len(packs)} avatars classified)", file=sys.stderr)
    print(f"  - report.md", file=sys.stderr)
    print(f"  - tokens_<pack>.tsv x {len(packs)}", file=sys.stderr)


if __name__ == "__main__":
    main()
